### ISSUE TITLE
Cleanup and future work: Parsing module

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/uosql-server#51]
This issue is part of the _first weekend cleanup_.

---

After looking through your code I have found a few things worth noting. You can decide if you want to fix something or not, but I highly recommend fixing everything!
- The `token::Lit` type has the variant `Int(String)`. This doesn't make a whole lot of sense: The lexer should already convert the string to an integer. Yes there are some problems with huge integers, but in that case we would some when use `BigInt`. So: Convert any integer literal into a `i64` or something already in the lexer.
- Why is there a `Token::Num` and a `Lit::Int`? Any numbers inside the query string are integer literals and should have the type `Lit::Int`.
- You just make all chars in all words lowercase... I'd say that's totally not what we want. Table names should be case sensitive. If you have some good reasons, ask me in person.
- In line 219 of `lex.rs` you first call `scan_lit` and `bump` afterwards. All `scan_` methods should bump enough such that `curr` is the first character after the scanned something. Since the closing `"` or `'` is part of the literal, `scan_lit` should `bump()` once more.
- You should remove any notion of whitespace in the parser. The lexer should handle whitespace itself. In my Java parser I have a `next_real` method of the lexer that returns the next token which is not a whitespace token.
- This crazy while condition in line 170 (`parser.rs`) should be changed. For example: `while self.curr.unwrap_or(Token::Unknown) != Token::ParenCl {`.
- You should use `expect_*` methods not to check if the current token is XY. You should imagine that `expect_*` will always error if the token is not in the given list. `expect_*` returning an error means that the SQL string is ill-formed and it will ALWAYS interrupt the whole parsing. There should always be a `try!()` around calls to those methods.
- The `SqlType` type should probably live in `storage`. Will talk to you in person about that.

**Comment by sheyderich** [comment]
Replacing that crazy condition would result in a much more complicated solution required than you expect.

**Comment by sheyderich** [comment]
expect_\* doesn't always indicate ill-formed querys when returning Err(e).
It just means that the expected \* wasn't found.
Example:
delete from x  <- valid statement, expected but optional where not found
delete from x where y=z <- valid statement
