### ISSUE TITLE
Cleanup and future work: Network

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/uosql-server#52]
This issue is part of the _first weekend cleanup_.

---

After looking through your files on the weekend I found a few things that are worth noting, some of which are just my opinion and don't _need_ to be applied.
- Your type `Cnv` still derives `RustcEncodable` and `RustcDecodable`, but it's not used anywhere. So you could remove the derive attribute, or much better: Use it. Currently there are lots of `as u8` and `as Cnv` in your code. You can change all your `(read|write)_u8`s to `encode` or `decode`s. That way you won't need to cast any more (avoiding `as` casts is a good thing).
- About `Cnv` again: I would call it `PacketType` or `PkgType` and call it's variants `Greet`, `Login`, ... (without the redundant `Pkg`). `PgkType::Greet` says much more to the reader than `Cnv::GreetPgk`.
- I would also rename `NetworkErrors`. First of all: Think of how it's written from the "users" perspective: `NetworkErrors::IoError` or even `net::NetworkErrors::IoError`. My suggestion is to call it `Error` (it living in module `net` already says that it's about network errors) and call it's variants: `Io`, `Encoding`, `Decoding`, ... (now it's `net::Error::Io` - nice)
- The method `Login::new()` is never used, so you should remove it. If you want that type with empty strings you can also `derive(Default)` which will provide a `Login::default()` method that will do exactly what you want.
- Some `to_string`s are replaceable with `into`
- In line 147, 181 and 224 are some things that can be shortened (see below).
- I think it would be very wise to restructure your work, especially the client's code. See below. (This is also the reason why I did not clean up nor comment on the client code).
### map and map_err at your service

In line 147 you have this:

``` rust
// receive login data from client
let login = read_login(stream);
match login {
    Ok(sth) => Ok((sth.username, sth.password)),
    Err(msg) => Err(msg)
}
```

It may look ok first, but the line `Err(msg) => Err(msg)` looks redundant at second glance. What you want is just to change the _ok_-value of the `Result`. Luckily Rusts `Option` and `Result` types have plenty of nice methods for uses like that. To change the _ok_-value there is a method called `map`. Like it's name suggest it maps a value to another one. It would work like this for your example:

``` rust
read_login(stream).map(|sth| (sth.username, sth.password))
```

On the left side simply have the `Result` returned by `read_login`. On that result we call the method `map` and pass a closure as argument. That closure takes the _ok_-value and generates something new (a tuple in this case).

The implementation of `map` is fairly simple so I want to use it to explain it:

``` rust
pub enum Result<T, E> {
    Ok(T),
    Err(E)
}

impl<T, E> Result<T, E> {
    pub fn map<U, F: FnOnce(T) -> U>(self, op: F)
        -> Result<U, E>
    {
        match self {
            Ok(t) => Ok(op(t)),
            Err(e) => Err(e)
        }
    }
}
```

The enum definition should be rather easy to understand. We have two generic type parameters: `T` the _ok_-type and `E` is the _error_-type. The `map` function takes two parameter: `self` and something of type `F`, which is a generic type parameter and is bounded to be a `FnOnce(T) -> U`. This only means that `F` needs to be a function-like thing that will accept the type `T` as parameter and returns something of type `U` (where type `U` may be anything). `map` returns a `Result<U, E>` (remember: before it was a `Result<T, E>`). And the function body looks a lot like your code in `net.rs`. The important part is that in case of `Ok`, the _ok_-value is passed into that function and the result is wrapped in the `Ok` that is returned.

After some time it should be rather clear how this works.

The same thing is applicable to two of your blocks starting in line 181 and 224. The only difference is that we want to change the _error_-value and not the _ok_-value there. Gladly Rust has a function for that too: `map_err`.
### Restructuring for fun and profit

Your code works and is fine, but it is not structured perfectly. Imagine that we want to write another application that wants to communicate with the database server. In that case we would have a lot of duplicate code in both applications. For other databases (like MySQL and Postgresql) there exist several libraries for many languages. Those libraries contain functionality to communicate with the database server (aka. all your client side network stuff). If we want to create an awesome database server, we should offer an easy way to communicate with it.

My plan is: All client code that has to do with networking is moved into it's own library and your client uses this library to do everything it does. To see an example of such a library, you can look at the Rust library for Postgresql [here](http://sfackler.github.io/rust-postgres/doc/v0.9.6/postgres/). But I will talk to you in person about that.

It also requires some restructuring of the whole project, which will probably done tomorrow (EDIT: done).

To start, I'd recommend doing this:
- Create a `net` folder where the old `net.rs` is living and `git mv net.rs net/mod.rs`
- Create a file `types.rs` in the net folder and import that module with `pub mod types;` as well as reexporting it's symbols with `pub use types::*;`
- Now move all enum and struct definitions that are being send over network (often via serialization) into the `types` submodule. Imagine that the client is only able to access your `types` module and nothing from the root-net-module (which, at that point, should contain methods only for server use)

**Comment by SvantjeJung** [comment]
Done (#64)
