### ISSUE TITLE
Cleanup and future work: Storage

### ISSUE THREAD

**Issue by LukasKalbertodt** [OsnaCS/uosql-server#56]
Cleanup and future work: Storage

This issue is part of the _first weekend cleanup_.

---

I have some plans for your storage module and in this issue I will define what works need to be done next. First of all: You should split your module in several files. I suggest the following:
- in the root (`mod.rs`) only lives the `Engine` trait for now
- in the file `meta.rs` are all types and functions that are for writing some kind of meta data to the filesystem (`Database` and `Table`)
- the file `data.rs` contains all symbols for writing "real data" to file (more information below)
- the submodule `engine` in `engine/mod.rs` contains all storage engine implementations

The files `meta.rs` and `data.rs` are not real submodules in the sense that they are publicly reexported. That works by including the module with `mod meta;` (notice the missing `pub`) and by reexporting all symbols with `pub use meta::*;`. That way no one will be able to access it via `storage::meta::bla`, but only via `storage::bla` -- such as the submodule `meta` does not exist at all. 

However, the submodule `engine` is not publicly reexported and needs to be included with `pub mod engine;`. All storage engine implementations which life in seperate files (like `flatfile.rs`) will again be reexported by the `engine` module, such that the a path would be `storage::engine::FlatFile` instead of `storage::engine::flatfile::FlatFile`. 
### New code

After (!!) restructure from above is done, there are some things to work on.
#### Types

The type `SqlType` should live in the submodule `types`. `SqlType` is an enum and needs a method `encode_into<W: Write>(&self, buf: W, data: ast::DataSrc) -> Result<u32, Error>`. `ast::DataSrc` will be a type that can represent any literal in an sql query (string literals, numbers, ...). The method should write a compact binary representation into `buf`, if possible. It will contain a huge `match` block for all SqlTypes and in each arm of that block the data for the type is written, if the literal was of the right type. The number of written bytes should be returned if everything is ok, and appropriate error otherwise.
#### Column

A column needs more data besides type and name. For example: An optional default value for the column and if it may be null.
#### Engine insert

The storage engine needs a new method `insert_row(&mut self, data: &[Option<ast::DataSrc>]) -> Result<(), Error>`. The slice of optional `ast::DataSrc` is a slice with as many elements as there are column (you can even `panic!()` if that's not true, if you like). None means that no value was given for that column and the default value should be inserted. The default value can be queried through the table's columns. This method will actually just call `SqlType::encode_into`, aggregates the data in a Vec and writes it into file.
#### Rows

It lives in `data.rs`. It is not directly usable but you can implement the shell already: `Rows` has a `Vec<u8>` for all the row data and a reference to a table. 
#### Engine full_scan

The storage engine should have the method `full_scan` that returns a `Rows` object that will store all rows from the table.

**Comment by Cranc** [comment]
#67 should implement the last things Rows  / Engine insert and Engine full_scan
Columns and types already contained in older pull request.

can close !
